name: Build macOS App

on:
  push:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install py2app

      - name: Criar setup.py temporário
        run: |
          echo "from setuptools import setup" > setup.py
          echo "APP = ['snaplist.py']" >> setup.py
          echo "OPTIONS = {'argv_emulation': True}" >> setup.py
          echo "setup(app=APP, options={'py2app': OPTIONS})" >> setup.py

      - name: Compilar app para macOS
        run: python setup.py py2app

      - name: Enviar como artefato
        uses: actions/upload-artifact@v4
        with:
          name: SnapList-macOS
          path: dist/*.app
