name: Build App with py2app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Usando Ubuntu porque macOS não está disponível para rodar em GitHub Actions nativamente
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py2app  # Instalar o py2app

      - name: Build the app
        run: |
          python setup.py py2app  # Rodar o py2app para criar o aplicativo

      - name: Upload app as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: dist/  # O diretório 'dist' onde o app será gerado
