from setuptools import setup
import py2app

APP = ['seu_app.py']
DATA_FILES = ['log.png', 'icone.ico']  # Adicione os arquivos de imagem aqui
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'icone.ico',  # O ícone do aplicativo (usualmente um arquivo .icns no macOS)
    'packages': ['flet', 'yt_dlp'],  # Liste suas dependências aqui
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
