name: Build macOS App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py2app

      - name: Build app with py2app
        run: |
          python setup.py py2app

      - name: Upload built app
        uses: actions/upload-artifact@v4
        with:
          name: mac-app
          path: dist/*.app
